name: website

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: master
          build_dir: build
          fqdn: arnavsankaran.com
        env:
          GITHUB_PAT: ${{ secrets.DEPLOY_TOKEN }}
